version: '3'
services:
  previews:
    build: .
    environment:
      - PLEX_URL=https://xxxxxx.plex.direct:32400 # can also input http://localhost:32400
      - PLEX_TOKEN=your-plex-token # fetch it from your media xml
      - PLEX_BIF_FRAME_INTERVAL=5
      - THUMBNAIL_QUALITY=4
      - PLEX_LOCAL_MEDIA_PATH=/path/to/plex/media
      - TMP_FOLDER=/tmp/previews
      - PLEX_TIMEOUT=60
      - GPU_THREADS=4  
      - CPU_THREADS=4
##if u want to use it remotely 
#      - PLEX_LOCAL_VIDEOS_PATH_MAPPING=/videos ## 
#      - PLEX_VIDEOS_PATH_MAPPING=/path/to/plex/videos
    volumes:
      - /path/to/plex/media:/path/to/plex/media
      - /path/to/plex/videos:/videos
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia