# Use the same base image as your production Dockerfile
FROM linuxserver/ffmpeg:7.0.1

# Install Python, pip, and other dependencies
RUN apt-get update && apt-get install -y \
    mediainfo \
    software-properties-common \
    gcc \
    musl-dev \
    python3 \
    python3-pip \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file and install Python dependencies
COPY requirements.txt .
RUN pip3 install --user -r requirements.txt

# Install additional development tools if needed
# For example, install pylint for linting
RUN pip3 install --user pylint

# Ensure the Python user base binary directory is in PATH
ENV PATH="/root/.local/bin:${PATH}"

# Copy the rest of the application code
COPY src/ ./src
COPY config/.env.example .env.example

# Set environment variables (optional)
# ENV PLEX_URL=http://localhost:32400
# ENV PLEX_TOKEN=your_token_here

# Set the default command to bash for an interactive terminal
CMD ["/bin/bash"]
